/**
 * Utility functions for xterm.js terminal management
 */

/**
 * Detects terminal-internal control sequences that should not be sent to the shell.
 * These are generated by xterm.js internally for terminal management (color queries, etc.)
 *
 * Filters:
 * - OSC (Operating System Command): ESC ] ... ST or ESC ] ... BEL
 *   Examples: color queries/sets, window title, clipboard operations
 * - DCS (Device Control String): ESC P ... ST
 *   Examples: sixel graphics, user-defined keys
 * - PM (Privacy Message): ESC ^ ... ST
 * - APC (Application Program Command): ESC _ ... ST
 *
 * Background:
 * When xterm.js initializes, it may query the terminal environment by sending
 * OSC sequences (e.g., OSC 10 for foreground color, OSC 11 for background color).
 * In TTY mode, the onData handler captures ALL data, including these internal
 * sequences. Without filtering, they would be sent to the shell as user input,
 * causing unwanted text to appear in the terminal.
 *
 * @param data - The data string from xterm's onData event
 * @returns true if the data is a terminal-internal sequence, false otherwise
 *
 * @example
 * isTerminalInternalSequence('\x1b]10;rgb:c9c9/d1d1/d9d9\x1b\\') // true (OSC 10)
 * isTerminalInternalSequence('\x1b]11;rgb:1a1a/1a1a/1a1a\x1b\\') // true (OSC 11)
 * isTerminalInternalSequence('ls -la') // false (regular input)
 * isTerminalInternalSequence('\r') // false (Enter key)
 */
export function isTerminalInternalSequence(data: string): boolean {
  // OSC sequences: ESC ] ... (ESC \ or BEL)
  // Format: \x1b] ... \x1b\ or \x1b] ... \x07
  // Common examples:
  // - OSC 0: Set window title
  // - OSC 10: Set/query foreground color
  // - OSC 11: Set/query background color
  // - OSC 52: Clipboard operations
  if (data.startsWith('\x1b]')) {
    return true;
  }

  // DCS sequences: ESC P ... ESC \
  // Format: \x1bP ... \x1b\
  // Examples: sixel graphics, user-defined keys
  if (data.startsWith('\x1bP')) {
    return true;
  }

  // PM sequences: ESC ^ ... ESC \
  // Format: \x1b^ ... \x1b\
  // Used for privacy messages
  if (data.startsWith('\x1b^')) {
    return true;
  }

  // APC sequences: ESC _ ... ESC \
  // Format: \x1b_ ... \x1b\
  // Application program commands
  if (data.startsWith('\x1b_')) {
    return true;
  }

  return false;
}

/**
 * Check whether the terminal's current mouse-tracking mode supports wheel events.
 *
 * xterm.js sets `terminal.modes.mouseTrackingMode` when a TUI application
 * (e.g., vim, htop) enables mouse reporting via DECSET escape sequences.
 * Relevant modes:
 *   - `'vt200'`     — normal tracking (press + release, includes wheel buttons 4/5)
 *   - `'drag'`      — button-event (drag) tracking (includes wheel)
 *   - `'any'`       — any-event tracking (includes wheel)
 *   - `'x10'`       — basic press-only tracking (NO wheel support)
 *   - `'vt200Highlight'` — highlight tracking (rarely used)
 *   - `'none'`      — mouse tracking is off
 *
 * Modes `'vt200'`, `'drag'`, and `'any'` include wheel-button codes (64/65)
 * in their reports, so the TUI already handles wheel events.  Returning
 * `true` tells the caller to let xterm.js forward the event to the TUI
 * instead of performing normal scrollback scrolling.
 *
 * @param mode - The value of `terminal.modes.mouseTrackingMode`
 * @returns `true` when the active mode reports wheel events
 */
export function supportsWheelMouseTracking(mode: string): boolean {
  return mode === 'vt200' || mode === 'drag' || mode === 'any';
}
